#SPDX-License-Identifier: MIT-0
---
# tasks file for ssl_certificate

- name: Add Certbot PPA
  apt:
    ppa: certbot/certbot
    state: present
    update_cache: yes

- name: Install Certbot and Nginx
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain SSL certificate using Certbot
  command: certbot --nginx --non-interactive --agree-tos -m "{{ cert_email }}" -d "{{ domain_name }}"
  register: certbot_result
  ignore_errors: true

- name: Create nginx file for redirecting HTTP to HTTPS
  template:
    src: redirect.j2
    dest: /etc/nginx/sites-available/redirect
  notify: Reload Nginx

- name: Enable redirect configuration in Nginx
  file:
    src: /etc/nginx/sites-available/redirect
    dest: /etc/nginx/sites-enabled/redirect
    state: link
  notify: Reload Nginx

- name: Ensure SSL certificate is renewed
  cron:
    name: "Renew SSL certificates"
    minute: "0"
    hour: "0"
    job: "/usr/bin/certbot renew --quiet && systemctl reload nginx"
    state: present