#SPDX-License-Identifier: MIT-0
---
# tasks file for setup_clb

- name: Create a Classic Load Balancer (CLB)
  amazon.aws.elb_classic_lb:
    name: "my-clb"
    subnets:
      - "subnet-08e371e4b8b878c1c"  # Replace with your subnet ID
    security_group_ids:
      - "sg-0fcf50bd3fd24b843"  # Replace with your security group ID
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 5000
    state: present
    region: "eu-south-2"
  register: clb

- name: Gather information about web server instances
  amazon.aws.ec2_instance_info:
    filters:
      "tag:Name": "web-server"  # Replace with your tag key and value
      "instance-state-name": "running" # Filter for running instances only
    region: "eu-south-2"
  register: ec2_info

- name: Register web server instances with the CLB
  amazon.aws.elb_classic_lb:
    name: "my-clb"
    instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
    state: present
    region: "eu-south-2"