#SPDX-License-Identifier: MIT-0
---
# tasks file for python

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install all required dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-setuptools
    - python3-pip
    - python3-venv
    - python3-dev
    - build-essential
    - python3-mysqldb