#SPDX-License-Identifier: MIT-0
---
# tasks file for setup_sg

- name: Create Security Group
  amazon.aws.ec2_security_group:
    name: ansible-sg
    description: "Security group with custom rules"
    vpc_id: "vpc-06c3e76e67fcb0ddd"   # Replace with your VPC ID
    region: "eu-south-2"              # Replace with your AWS region
    state: present
  register: security_group

- name: Add Custom Rule
  amazon.aws.ec2_security_group:
    name: ansible-sg
    description: "Security group with custom rules"
    vpc_id: "vpc-06c3e76e67fcb0ddd"
    region: "eu-south-2"
    state: present
    rules:
      # Custom TCP Port 5000
      - proto: tcp
        from_port: 5000
        to_port: 5000
        cidr_ip: 0.0.0.0/0
      # SSH (22)
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      # HTTP (80)
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      # Allow outbound HTTPS traffic to reach AWS EC2 status endpoint
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      # Self-referencing rule
      - proto: all
        from_port: -1
        to_port: -1
        group_id: "{{ security_group.group_id }}"
  #when: security_group.changed  # Only run if the SG was just created

- name: Debug created Security Group
  debug:
    msg: "Security Group {{ security_group.group_id }} created successfully."